### ISSUE TITLE
Attempt to parse a schema containing `.transform()` results in a type error

### ISSUE THREAD

**Issue by andreww2012** [andrewvo89/zod-error#2]
First of all, thank you for this nice library!

Both `parse` and `parseAsync` produce type errors when I'm trying to parse a schema containing `.transform()` (the example is directly taken from the zod docs):

```ts
import z from 'zod';
import {parse, parseAsync} from 'zod-error';

const stringToNumber = z.string().transform((val) => val.length);

// No error:
stringToNumber.parse('string');

// Argument of type 'ZodEffects<ZodString, number, string>' is not assignable to parameter of type 'ZodType<number, ZodTypeDef, number>'.
//  Types of property '_input' are incompatible.ts(2345)
parse(stringToNumber, 'string');

// Argument of type 'ZodEffects<ZodString, number, string>' is not assignable to parameter of type 'ZodType<number, ZodTypeDef, number>'.ts(2345)
parseAsync(stringToNumber, 'string'); 
```

**Comment by andrewvo89** [comment]
Hi @andreww2012, can you please confirm the versions of both `zod` and `zod-error` you are using?

**Comment by andreww2012** [comment]
Hey, sorry for the lack of information about versions in the initial message.

I'm using `zod@3.20.2`, `zod-error@1.1.0` and `typescript@4.9.4`.

**Comment by andrewvo89** [comment]
Thank you @andreww2012.

I have confirmed the issue and rectified it with a new release. Please update to `zod-error@1.1.1`.

**Comment by andreww2012** [comment]
Thank you. This did fix the problem!
