### ISSUE TITLE
Does `generateError()` work in the frontend?

### ISSUE THREAD

**Issue by SomiDivian** [andrewvo89/zod-error#5]
It returns a string of ZodError
```cli
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [
      "field"
    ],
    "message": "Expected string, received number"
  }
]
```

it works fine on the server though
```cli
Code: invalid_type ~ Path: field ~ Message: Expected string, received number
```

## Code
```ts
// demo.server.ts
async function handleDemo() {
  const data = isValid({
    field: 00,
  });
  console.log(data);
  // 'Code: invalid_type ~ Path: field ~ Message: Expected string, received number'

  return new Response("ok", { status: 200 });
}

// front end
const Schema = z.object({
  field: z.string(),
});

function isValid(args: unknown) {
  try {
    const data = Schema.parse(args);

    return data;
  } catch (error) {
    const err = generateError(error);

    return err.message;
  }
}

export default function Demo() {
  return (
    <div>
      <button
        onClick={() => {
          const data = isValid({
            field: 00,
          });
          console.log(data);
          // '[ ... ]'
        }}
      >
        Check
      </button>
    </div>
  );
}

```

**Comment by SomiDivian** [comment]
By the way, if you host this library yourself, it works

**Comment by andrewvo89** [comment]
Hi @SomiDivian, I have re-created your code on codesandbox and unfortunately cannot reproduce your bug.
Looking through the source code, there's no way the generateError() function returns a stringified ZodError. You might need to double check your code to see if there is something else going on.

https://codesandbox.io/s/https-github-com-andrewvo89-zod-error-issues-5-i3odvs?file=/src/App.tsx

**Comment by SomiDivian** [comment]
Check this out, next.js, same for remix.js

https://codesandbox.io/p/sandbox/tender-leftpad-km5194?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A36%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A36%7D%5D

**Comment by andrewvo89** [comment]
Thanks, I can't really explain why it doesn't work on next.js or remix.js. Might be something got to do with server side rendering which is beyond my knowledge. I can however suggest an alternative way to use the API for your `isValid()` function.

```ts
export function isValid(args: unknown) {
  const parsed = Schema.safeParse(args);
  if (!parsed.success) {
    return generateErrorMessage(parsed.error.issues);
  }
  return parsed.data;
}
```

**Comment by SomiDivian** [comment]
thanks
