### ISSUE TITLE
Doesn't handle unions well

### ISSUE THREAD

**Issue by Thinkscape** [andrewvo89/zod-error#6]
Example schema:
```ts

const a = z.object({
  foo: z.string()
});

const b = z.object({
  bar: z.string()
});

const schema: z.union([a, b]);
```

Example error:
```json
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "null",
            "path": [
              "foo"
            ],
            "message": "Expected string, received null"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "bar"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
```

`generateErrorMessage()` gives me:

```
Code: invalid_union ~ Path:  ~ Message: Invalid input
```

**Comment by andrewvo89** [comment]
Hi @Thinkscape , please see https://github.com/andrewvo89/zod-error/issues/4#issuecomment-1439861157 for an example on how you can access the inner `unionErrors` property to use for your final error message.

**Comment by Thinkscape** [comment]
I'm confused with why would the `transform` implementation you've suggested not be integral part of `generateErrorMessage()` ?

My userland expectation was that I'd be able to use `zod-error`, with sane defaults, to generate error messages for any schema issues (recursively). If I need to massage the error further in order for zod-error to be happy, IMHO it defeats the purpose of using zod-error in the first place.

Or, looking from the return value perspective, current implementation can't handle empty `path` and is not recursive, which means it breaks with certain schemas. `unionErrors` would probably be just an example of one, but there might be others.

**Comment by Thinkscape** [comment]
For reference, here's my naive, opinionated no-deps alternative that handles it correctly:

https://gist.github.com/Thinkscape/d85d761335aa73ea0db59845d6aa9f1f

**Comment by andrewvo89** [comment]
Hey @Thinkscape, try this:
```ts
  const a = z.object({
    foo: z.string(),
  });

  const b = z.object({
    bar: z.string(),
  });

  const schema = z.union([a, b]);

  const parsed = schema.safeParse(null);
  if (!parsed.success) {
    const generated = generateErrorMessage(parsed.error.errors, {
      transform: ({ issue, codeComponent, errorMessage, messageComponent, pathComponent }) => {
        // This your standard default messaging
        let defaultMsg = `${codeComponent} ~ ${messageComponent} ~ ${pathComponent} ~ ${errorMessage}`;

        // This is the custom messaging for the union error
        if (issue.code === 'invalid_union') {
          return `${defaultMsg} ~ Enum errors: ${issue.unionErrors
            .map((unionError) => JSON.stringify(unionError.issues))
            .join(', ')}`;
        }

        return defaultMsg;
      },
    });

    console.log(generated);
    // Code: invalid_union ~ Message: Invalid input ~ Path:  ~ Code: invalid_union ~ Path:  ~ Message: Invalid input ~ Enum errors: [{"code":"invalid_type","expected":"object","received":"null","path":[],"message":"Expected object, received null"}], [{"code":"invalid_type","expected":"object","received":"null","path":[],"message":"Expected object, received null"}]
```

**Comment by Thinkscape** [comment]
Thanks Andrew.
It does the job, but my point was about having this built/bundled into `zod-error` instead of having to manually come up with a transformer for each version of my schemas.

**Comment by andrewvo89** [comment]
> Thanks Andrew. It does the job, but my point was about having this built/bundled into `zod-error` instead of having to manually come up with a transformer for each version of my schemas.

I understand and PRs are welcome if you would like this feature sooner than later. But it is noted as a future improvement.
